spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/demojob?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: job-backend
    server: http://localhost:${server.port}
    title: Job Backend
    version: 1.0.0
jwt:
  expiryMinutes: 60
  expiryDay: 14
  accessKey: 2ae7169e42e0eda06311a44e328cbd898f4efa93eebbe34e904f145b3cf2f9050d03ca6c655f6222fcfa370936d8f00f4b14d9e6eef82c7881772de5c5d45d91
  refreshKey: 1dfd139524df02ff57b6cb9887a2b24603119ed004337b88c4f64a7e554b2ffd3f43efd1a306b61475d292ec932113022dd04c10fc5ce2cfba2658abef0cc249
  secretKey: deeab47aded1451b3aa82afe58f84f73d797e223f671996d417eb0afdc80d44869622e9161ecba9b066ca334dd706b63fd67d3e66fc981dbbe2c19302d456c07
