spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/demojob?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: job-backend
    server: http://localhost:${server.port}
    title: Job Backend
    version: 1.0.0
jwt:
  expiryMinutes: 60
  expiryDay: 14
  accessKey: 3e76a20f14870544fe9769b171033cbf255be28127e3376903ba47c06bc30e4a13463f5de47fa3ccbc1631de77e2c0c78eeb007c5ad395f9d028a82b8cffbd32
  refreshKey: 2d30952bbe2be2910fcd7d10af97e0836b990808792f2d37ad99789f0cf99b1ac35a77e19cee88e601dfbc6e12389f391e17a0cdb91e0f78a0eb7dad380da082
  secretKey: 4db44c56d1e29e7d6279e8c27d2d29c8b07d411dd009f7949e446866b0230944ba177a487adb0eaca6f5ec8dc153c9cc78b65fd0b9c8ace23f6a6ed6373c3f9b
file:
  upload-dir: file:///D:/springbootproject/project/upload/
