server:
  port: 8080
spring:
  application:
    name: job-backend
  profiles:
    active: @spring.profiles.active@

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
#  endpoint:
#    health:
#      probes:
#        enabled: true
#  health: # config for EKS
#    livenessState:
#      enabled: true
#    readinessState:
#      enabled: true
#  prometheus:
#    metrics:
#      export:
#        step: 5s
#        enabled: true

# Logging
logging:
  level:
    root: INFO
    web: INFO
#    org.springframework: INFO
#    org.apache: OFF
#    kafka: OFF
